In [9]:
from transforms import PreprocessTransform
from torch_geometric.data import Data
import torch
from objects import MultiScaleData
num_nodes = 6
edge_index = torch.stack([
    torch.arange(num_nodes),
    torch.arange(1,num_nodes + 1) % num_nodes
])
edge_index = torch.cat([edge_index,edge_index.flip(0)],-1)
edge_index = torch.cat([edge_index,edge_index + num_nodes],-1)
num_nodes *= 2
edge_attr = torch.zeros(edge_index.size(1))
data : MultiScaleData= PreprocessTransform()(Data(torch.zeros(num_nodes),edge_index=edge_index,edge_attr=edge_attr,num_nodes=num_nodes))

In [13]:
print(data.edge_index_edge.size())
from torch_geometric.utils import degree
print(degree(data.edge_index_edge[0]),degree(data.edge_index_edge[1]))
print(data.num_cycles)
print(data.edge_index_edge_cycle)
print(data.edge_attr_cycle)
print(data.edge_attr_cycle_edge)
print(data.cycle_edge_cycle_indicator)

torch.Size([2, 288])
tensor([12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.,
        12., 12., 12., 12., 12., 12., 12., 12., 12., 12.]) tensor([12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.,
        12., 12., 12., 12., 12., 12., 12., 12., 12., 12.])
2
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1]])
tensor([6, 6])
tensor([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6